// Battle Mind Creative: one content source for all 7 builds.
// Facts come from battlemind.my (scraped 2026-09-28). The copy is condensed rather than transcribed.
window.BM = {
  name: "Battle Mind Creative",
  short: "Battle Mind",
  city: "Kuala Lumpur",
  eyebrow: "Performance-driven digital marketing · Kuala Lumpur",
  headline: ["Performance-Driven", "Digital Marketing", "Agency"],
  sub: "A data-intelligent online advertising agency in KL — specialists in social media, web search and short video.",
  mantra: [
    ["Sales", "Engagement"],
    ["Results", "Hype"],
    ["Leads", "Likes"],
  ],
  cta: { label: "Start now", href: "https://wa.me/60197707927" },
  stats: [
    { n: 200, suffix: "+", label: "clients served across Malaysia & beyond" },
    { n: 25, prefix: "20–", suffix: "%", label: "typical annual sales lift after engaging us" },
    { n: 40, suffix: "%+", label: "YoY monthly sales growth reported by loyal clients" },
    { n: 7, suffix: "", label: "disciplines under one battle-tested roof" },
  ],
  // Brand lines from the Battle brand guidelines (2026): "Built For Growth.", "Strategy. Creative. Performance.",
  // and the boardroom wall "Focus · Build · Win".
  brandline: "Built For Growth.",
  pillars: ["Strategy", "Creative", "Performance"],
  wall: ["Focus", "Build", "Win"],
  story: [
    { k: "01", tag: "Focus", img: "st_ch1_focus",
      title: "Focus on one number.",
      body: "Every engagement starts with “What’s your business objective?” We aim at that number, not at vanity metrics." },
    { k: "02", tag: "Build", img: "st_ch2_build",
      title: "Build the engine.",
      body: "Paid social, search, short video, creators and a site that converts, all assembled around the same target." },
    { k: "03", tag: "Perform", img: "st_ch3_perform",
      title: "Strategy. Creative. Performance.",
      body: "Seven disciplines work as one system, so every ringgit you spend compounds instead of competing." },
    { k: "04", tag: "Win", img: "st_ch4_win",
      title: "Built for growth.",
      body: "Clients typically grow sales 20–25% a year with us. Some have scaled almost 4× in under two years." },
  ],
  about: {
    kicker: "Not your average marketing team",
    title: "Battle-tested. Entrepreneur-minded.",
    body: [
      "We started out helping startups find their first customers. Since then we’ve run campaigns for global giants, and earned our stripes (and lost a little hair) along the way.",
      "Today we help SMEs grow sales by millions a year. We think like founders and stay fixed on your objective, and we don’t upsell services you don’t need.",
    ],
    person: { name: "Matthew Leong", role: "Business Director", img: "Battle-Mind-about-us-v3" },
  },
  services: [
    { id: "social", name: "Facebook + Instagram Marketing", short: "Social Ads", img: "st_svc_social",
      line: "Paid social that sells, not just scrolls.",
      points: ["Strategy, content pillars & calendar", "Meta, LinkedIn & TikTok ads", "Audience targeting & analytics", "Monthly reporting & optimisation"] },
    { id: "seo", name: "SEO + SEM", short: "Search", img: "st_svc_seo",
      line: "Be found the moment they search.",
      points: ["Technical audits & keyword strategy", "On-page, off-page & backlinks", "Google Search, Display & Shopping", "Landing pages & A/B testing"] },
    { id: "video", name: "Ad-Video Production", short: "Video", img: "st_svc_video",
      line: "Short, snappy video built for the feed.",
      points: ["Brand story & product demo", "Testimonials & interviews", "Social ads & behind-the-scenes", "Monthly storytelling series"] },
    { id: "kol", name: "Influencer Marketing", short: "KOL", img: "st_svc_influencer",
      line: "Creators whose audience is your customer.",
      points: ["Audience-fit KOL selection", "Facebook, IG, TikTok, XHS, YouTube", "Brief, review & brand safety", "Boost winning UGC as paid ads"] },
    { id: "creative", name: "Creative + Design", short: "Design", img: "st_svc_creative",
      line: "Design that triggers action.",
      points: ["Ad creatives & social visuals", "Packaging & sales kits", "On-brand across print and web", "2 revision rounds as standard"] },
    { id: "branding", name: "Branding", short: "Brand", img: "st_svc_branding",
      line: "A voice, a vision, a lasting mark.",
      points: ["Brand workshops & positioning", "Naming, tagline & logo", "Brand kits & guidelines", "Rebranding for new markets"] },
    { id: "web", name: "Website & App Development", short: "Web", img: "st_svc_web",
      line: "Sites that convert the traffic we send.",
      points: ["Conversion-first websites", "Landing pages for campaigns", "E-commerce & web apps", "Tracking wired in from day one"] },
  ],
  logos: ["Arla-logo-v2","Colgate-logo-v2","Tesla-logo","Manchester-United-logo-v2","Liverpool-logo-v2","Good-Year-logo-v2",
    "Grab-Express-logo-v2","Maxis-Business-logo","Tupperware-logo","Entropia-logo-v2","Hovid-logo-v2","Softlan-logo-v2",
    "Puck-logo-v2","Naturel-logo-v2","Citrex-logo-v2","Dasiy-logo-v2","Bio-home-logo-v2","Easy-Europe-logo-v2",
    "Oktopurs-logo-v2","JOJO-logo-v2","Mr-Fish-logo-v2","Yaki-Soul-logo-v2","glo-logo-v2","Tiga-ikan-logo-v2",
    "Luxe-Living-logo-v2","sd-labs-logo-v2","Write-Edge-logo-v2","CR8-Melaka-logo-v2","BHP-Petrol-logo","BO-Capital-logo",
    "Aurea-logo","Campus-Rangers-logo","Fujian-Association-logo","Gemini-Spacecraft-logo","KAIA-logo","La-Gourmet-logo",
    "Magnet-Experiential-logo","Seng-Cars-World-logo","SWET-logo","Teien-logo","UBCT-logo","Yosen-logo","Zero-Healthcare-logo"],
  reviews: [
    { who: "Poi Ching", role: "General Manager, Write-Edge", img: "Poi-Ching",
      q: "Targeting the right audience helped us scale almost 4-fold in less than two years." },
    { who: "Elaine Tan", role: "Co-founder", img: "Elaine-Tan",
      q: "With the ads they manage on FB, my business had 30% growth in 3 months." },
    { who: "Marcus Teoh", role: "Bestselling Author & Speaker", img: "Marcus-Teoh",
      q: "My primary go-to Facebook/Instagram marketing solution whenever clients ask me for social help." },
    { who: "Cheanu Chew", role: "Network Marketing Coach", img: "Cheanu-Chew",
      q: "World-class professionalism — clients get the red-carpet treatment from first contact to execution." },
    { who: "Sheila", role: "Founder, SWET Image", img: "SWET-Image-International-Image-Branding",
      q: "Battle Mind truly lives up to their name — dynamic, creative, always going the extra mile." },
    { who: "Leonard Lai", role: "Founder", img: "Leonard-Lai",
      q: "Great, energetic, young but experienced — they pulled off great results on unusual products." },
  ],
  faq: [
    { q: "What does a digital marketing agency actually do for me?",
      a: "We cover the whole customer journey: SEO and SEM so people find you, ads on social and the web that reach them, then the website, content and video that convert them. Branding, KOL campaigns and market research are available when you need them." },
    { q: "How do you measure success?",
      a: "Against the business objective we agree on at the start. We project the numbers together, and a campaign succeeds when the final numbers beat that projection and the industry average." },
    { q: "Which industries do you know best?",
      a: "We've served hundreds of clients, and a large share come from tourism, F&B and FMCG." },
    { q: "How much does it cost in Malaysia?",
      a: "It depends on the target. Tell us the leads, reach or sales you want and we'll size the budget from your industry's benchmarks. Bigger goals need more budget." },
  ],
  contact: {
    address: "No. 7-2, Jalan 2/137B, Resource Industrial Centre, Off Jalan Kelang Lama, 58200 Kuala Lumpur",
    phone: "+6019-770 7927", tel: "+60197707927", email: "hello@battlemind.my",
  },
  legal: "© 2026 Battle Mind Creative Sdn Bhd 202001023398 (1379718-A)",
};
